### ISSUE TITLE
Allow user selection of evaluation strategy

### ISSUE THREAD

**Issue by fatho** [fatho/bachelor-thesis#4]
The evaluation strategy results from the choice of step index type and underlying non-determinism monad. The following are currently available:

**step index**
- natural numbers `n` (guarantees termination after a finite number of steps)
- `Infinity` (never reaches zero, interpreter runs indefinitely)

**non-determinism**
- list monad (depth first search, most likely only yields acceptable results for small `n`)
- [`control-monad-omega`](http://hackage.haskell.org/package/control-monad-omega-0.3.1/docs/Control-Monad-Omega.html) (some kind of breadth first search, guarantees to find all possible results after a finite number of steps, even if one branch turns out to be not terminating)
- other candidates are
  -  [`logict`](https://hackage.haskell.org/package/logict), but that requires the use of `MonadLogic` constraints in the interpreter instead of just `MonadPlus`
  - [`weighted-search`](http://hackage.haskell.org/package/weighted-search-0.1.0.1) which seems to require calls to `weight` inside the interpreter (which in turn would no longer be abstract over the underlying monad)

**Comment by jvoigtlaender** [comment]
The docu of `control-monad-omega` suggests to use `weighted-search` instead. If you want to enable use of `weighted-search` but not give up being able to abstract over the monad, couldn't you write the interpreter abstracted over a suitable concept/type-class `WeightedMonad`, i.e., monads with a `weight`-method? Then you should be able to instantiate this either with the monad from the `weighted-search` package or with any of the other search monads, by simply providing a general embedding that makes a `WeightedMonad` from every other `MonadPlus/Alternative` by adding a trivial implementation of `weight` (using a weight type that has only one element).

**Comment by fatho** [comment]
If I'm already going to introduce a new type class constraint in the interpreter, I would prefer using `MonadLogic` instead of rolling out my own type class, as it has some well-defined laws (as described in the [paper](http://okmij.org/ftp/papers/LogicT.pdf)) that `interleave` and `>>-` obey to whereas it is not really clear to me how `weighted-search` will behave without looking at the source code.

And if one insists to use unfair choice, one can always provide a newtype wrapper which implements `interleave` and `>>-` in terms of `mplus` and `>>=`.

**Comment by jvoigtlaender** [comment]
Sure. I was mainly commenting on `control-monad-omega` vs. `weighted-search`. (That the latter seems to supersede the former, and that the issue of an additional operation, and thus some loss of polymorphism, wouldn't need to be a reason to still prefer the former over the latter, if that was what you were planning to do.)

**Comment by fatho** [comment]
Is there a use case where one would want to use depth-first search instead of breadth-first search?
IMHO even with a limited number of steps, one would generally prefer BFS, since it yields the smaller results first, whereas the solutions generated by DFS would grow quickly in size.

**Comment by jvoigtlaender** [comment]
If we are going to have such discussions here rather than by email, should bring @mehner in.

**Comment by jvoigtlaender** [comment]
And the question of whether to support both BFS and DFS is relevant for @fanzier's thesis as well (in the operational semantics part).

**Comment by mehner** [comment]
I remember someone from the Kiel group saying DFS is approximately twice as fast. This led them to make BFS the default strategy. If the user believes the search space to be finite, he can get a speed-up, but if he is ignorant of the matter BFS will always be fine.
If there is going to be only one strategy, it should be BFS. Being able to switch to DFS is neat but not a must-have.
